// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: parser.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_parser_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_parser_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3008000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3008000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_parser_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_parser_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[5]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_parser_2eproto;
namespace ParserModel {
class BlobShape;
class BlobShapeDefaultTypeInternal;
extern BlobShapeDefaultTypeInternal _BlobShape_default_instance_;
class InferConfigParameter;
class InferConfigParameterDefaultTypeInternal;
extern InferConfigParameterDefaultTypeInternal _InferConfigParameter_default_instance_;
class ModelParameter;
class ModelParameterDefaultTypeInternal;
extern ModelParameterDefaultTypeInternal _ModelParameter_default_instance_;
class meanParameter;
class meanParameterDefaultTypeInternal;
extern meanParameterDefaultTypeInternal _meanParameter_default_instance_;
class normParameter;
class normParameterDefaultTypeInternal;
extern normParameterDefaultTypeInternal _normParameter_default_instance_;
}  // namespace ParserModel
PROTOBUF_NAMESPACE_OPEN
template<> ::ParserModel::BlobShape* Arena::CreateMaybeMessage<::ParserModel::BlobShape>(Arena*);
template<> ::ParserModel::InferConfigParameter* Arena::CreateMaybeMessage<::ParserModel::InferConfigParameter>(Arena*);
template<> ::ParserModel::ModelParameter* Arena::CreateMaybeMessage<::ParserModel::ModelParameter>(Arena*);
template<> ::ParserModel::meanParameter* Arena::CreateMaybeMessage<::ParserModel::meanParameter>(Arena*);
template<> ::ParserModel::normParameter* Arena::CreateMaybeMessage<::ParserModel::normParameter>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace ParserModel {

// ===================================================================

class BlobShape :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:ParserModel.BlobShape) */ {
 public:
  BlobShape();
  virtual ~BlobShape();

  BlobShape(const BlobShape& from);
  BlobShape(BlobShape&& from) noexcept
    : BlobShape() {
    *this = ::std::move(from);
  }

  inline BlobShape& operator=(const BlobShape& from) {
    CopyFrom(from);
    return *this;
  }
  inline BlobShape& operator=(BlobShape&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const BlobShape& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const BlobShape* internal_default_instance() {
    return reinterpret_cast<const BlobShape*>(
               &_BlobShape_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(BlobShape* other);
  friend void swap(BlobShape& a, BlobShape& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline BlobShape* New() const final {
    return CreateMaybeMessage<BlobShape>(nullptr);
  }

  BlobShape* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<BlobShape>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const BlobShape& from);
  void MergeFrom(const BlobShape& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  #else
  bool MergePartialFromCodedStream(
      ::PROTOBUF_NAMESPACE_ID::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::PROTOBUF_NAMESPACE_ID::io::CodedOutputStream* output) const final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(BlobShape* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "ParserModel.BlobShape";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_parser_2eproto);
    return ::descriptor_table_parser_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated int64 dim = 1 [packed = true];
  int dim_size() const;
  void clear_dim();
  static const int kDimFieldNumber = 1;
  ::PROTOBUF_NAMESPACE_ID::int64 dim(int index) const;
  void set_dim(int index, ::PROTOBUF_NAMESPACE_ID::int64 value);
  void add_dim(::PROTOBUF_NAMESPACE_ID::int64 value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int64 >&
      dim() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int64 >*
      mutable_dim();

  // @@protoc_insertion_point(class_scope:ParserModel.BlobShape)
 private:
  class HasBitSetters;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int64 > dim_;
  mutable std::atomic<int> _dim_cached_byte_size_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_parser_2eproto;
};
// -------------------------------------------------------------------

class meanParameter :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:ParserModel.meanParameter) */ {
 public:
  meanParameter();
  virtual ~meanParameter();

  meanParameter(const meanParameter& from);
  meanParameter(meanParameter&& from) noexcept
    : meanParameter() {
    *this = ::std::move(from);
  }

  inline meanParameter& operator=(const meanParameter& from) {
    CopyFrom(from);
    return *this;
  }
  inline meanParameter& operator=(meanParameter&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const meanParameter& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const meanParameter* internal_default_instance() {
    return reinterpret_cast<const meanParameter*>(
               &_meanParameter_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(meanParameter* other);
  friend void swap(meanParameter& a, meanParameter& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline meanParameter* New() const final {
    return CreateMaybeMessage<meanParameter>(nullptr);
  }

  meanParameter* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<meanParameter>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const meanParameter& from);
  void MergeFrom(const meanParameter& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  #else
  bool MergePartialFromCodedStream(
      ::PROTOBUF_NAMESPACE_ID::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::PROTOBUF_NAMESPACE_ID::io::CodedOutputStream* output) const final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(meanParameter* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "ParserModel.meanParameter";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_parser_2eproto);
    return ::descriptor_table_parser_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated float mean = 1;
  int mean_size() const;
  void clear_mean();
  static const int kMeanFieldNumber = 1;
  float mean(int index) const;
  void set_mean(int index, float value);
  void add_mean(float value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
      mean() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
      mutable_mean();

  // @@protoc_insertion_point(class_scope:ParserModel.meanParameter)
 private:
  class HasBitSetters;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< float > mean_;
  mutable std::atomic<int> _mean_cached_byte_size_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_parser_2eproto;
};
// -------------------------------------------------------------------

class normParameter :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:ParserModel.normParameter) */ {
 public:
  normParameter();
  virtual ~normParameter();

  normParameter(const normParameter& from);
  normParameter(normParameter&& from) noexcept
    : normParameter() {
    *this = ::std::move(from);
  }

  inline normParameter& operator=(const normParameter& from) {
    CopyFrom(from);
    return *this;
  }
  inline normParameter& operator=(normParameter&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const normParameter& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const normParameter* internal_default_instance() {
    return reinterpret_cast<const normParameter*>(
               &_normParameter_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  void Swap(normParameter* other);
  friend void swap(normParameter& a, normParameter& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline normParameter* New() const final {
    return CreateMaybeMessage<normParameter>(nullptr);
  }

  normParameter* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<normParameter>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const normParameter& from);
  void MergeFrom(const normParameter& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  #else
  bool MergePartialFromCodedStream(
      ::PROTOBUF_NAMESPACE_ID::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::PROTOBUF_NAMESPACE_ID::io::CodedOutputStream* output) const final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(normParameter* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "ParserModel.normParameter";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_parser_2eproto);
    return ::descriptor_table_parser_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated float norm = 1;
  int norm_size() const;
  void clear_norm();
  static const int kNormFieldNumber = 1;
  float norm(int index) const;
  void set_norm(int index, float value);
  void add_norm(float value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
      norm() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
      mutable_norm();

  // @@protoc_insertion_point(class_scope:ParserModel.normParameter)
 private:
  class HasBitSetters;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< float > norm_;
  mutable std::atomic<int> _norm_cached_byte_size_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_parser_2eproto;
};
// -------------------------------------------------------------------

class ModelParameter :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:ParserModel.ModelParameter) */ {
 public:
  ModelParameter();
  virtual ~ModelParameter();

  ModelParameter(const ModelParameter& from);
  ModelParameter(ModelParameter&& from) noexcept
    : ModelParameter() {
    *this = ::std::move(from);
  }

  inline ModelParameter& operator=(const ModelParameter& from) {
    CopyFrom(from);
    return *this;
  }
  inline ModelParameter& operator=(ModelParameter&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const ModelParameter& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ModelParameter* internal_default_instance() {
    return reinterpret_cast<const ModelParameter*>(
               &_ModelParameter_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  void Swap(ModelParameter* other);
  friend void swap(ModelParameter& a, ModelParameter& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ModelParameter* New() const final {
    return CreateMaybeMessage<ModelParameter>(nullptr);
  }

  ModelParameter* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<ModelParameter>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const ModelParameter& from);
  void MergeFrom(const ModelParameter& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  #else
  bool MergePartialFromCodedStream(
      ::PROTOBUF_NAMESPACE_ID::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::PROTOBUF_NAMESPACE_ID::io::CodedOutputStream* output) const final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ModelParameter* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "ParserModel.ModelParameter";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_parser_2eproto);
    return ::descriptor_table_parser_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .ParserModel.InferConfigParameter infer_config = 10;
  int infer_config_size() const;
  void clear_infer_config();
  static const int kInferConfigFieldNumber = 10;
  ::ParserModel::InferConfigParameter* mutable_infer_config(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::ParserModel::InferConfigParameter >*
      mutable_infer_config();
  const ::ParserModel::InferConfigParameter& infer_config(int index) const;
  ::ParserModel::InferConfigParameter* add_infer_config();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::ParserModel::InferConfigParameter >&
      infer_config() const;

  // string name = 1;
  void clear_name();
  static const int kNameFieldNumber = 1;
  const std::string& name() const;
  void set_name(const std::string& value);
  void set_name(std::string&& value);
  void set_name(const char* value);
  void set_name(const char* value, size_t size);
  std::string* mutable_name();
  std::string* release_name();
  void set_allocated_name(std::string* name);

  // @@protoc_insertion_point(class_scope:ParserModel.ModelParameter)
 private:
  class HasBitSetters;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::ParserModel::InferConfigParameter > infer_config_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr name_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_parser_2eproto;
};
// -------------------------------------------------------------------

class InferConfigParameter :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:ParserModel.InferConfigParameter) */ {
 public:
  InferConfigParameter();
  virtual ~InferConfigParameter();

  InferConfigParameter(const InferConfigParameter& from);
  InferConfigParameter(InferConfigParameter&& from) noexcept
    : InferConfigParameter() {
    *this = ::std::move(from);
  }

  inline InferConfigParameter& operator=(const InferConfigParameter& from) {
    CopyFrom(from);
    return *this;
  }
  inline InferConfigParameter& operator=(InferConfigParameter&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const InferConfigParameter& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const InferConfigParameter* internal_default_instance() {
    return reinterpret_cast<const InferConfigParameter*>(
               &_InferConfigParameter_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  void Swap(InferConfigParameter* other);
  friend void swap(InferConfigParameter& a, InferConfigParameter& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline InferConfigParameter* New() const final {
    return CreateMaybeMessage<InferConfigParameter>(nullptr);
  }

  InferConfigParameter* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<InferConfigParameter>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const InferConfigParameter& from);
  void MergeFrom(const InferConfigParameter& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  #else
  bool MergePartialFromCodedStream(
      ::PROTOBUF_NAMESPACE_ID::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::PROTOBUF_NAMESPACE_ID::io::CodedOutputStream* output) const final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(InferConfigParameter* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "ParserModel.InferConfigParameter";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_parser_2eproto);
    return ::descriptor_table_parser_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .ParserModel.BlobShape input_shape = 8;
  int input_shape_size() const;
  void clear_input_shape();
  static const int kInputShapeFieldNumber = 8;
  ::ParserModel::BlobShape* mutable_input_shape(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::ParserModel::BlobShape >*
      mutable_input_shape();
  const ::ParserModel::BlobShape& input_shape(int index) const;
  ::ParserModel::BlobShape* add_input_shape();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::ParserModel::BlobShape >&
      input_shape() const;

  // repeated .ParserModel.BlobShape output_shape = 9;
  int output_shape_size() const;
  void clear_output_shape();
  static const int kOutputShapeFieldNumber = 9;
  ::ParserModel::BlobShape* mutable_output_shape(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::ParserModel::BlobShape >*
      mutable_output_shape();
  const ::ParserModel::BlobShape& output_shape(int index) const;
  ::ParserModel::BlobShape* add_output_shape();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::ParserModel::BlobShape >&
      output_shape() const;

  // repeated .ParserModel.meanParameter mean_param = 10;
  int mean_param_size() const;
  void clear_mean_param();
  static const int kMeanParamFieldNumber = 10;
  ::ParserModel::meanParameter* mutable_mean_param(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::ParserModel::meanParameter >*
      mutable_mean_param();
  const ::ParserModel::meanParameter& mean_param(int index) const;
  ::ParserModel::meanParameter* add_mean_param();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::ParserModel::meanParameter >&
      mean_param() const;

  // repeated .ParserModel.normParameter norm_param = 11;
  int norm_param_size() const;
  void clear_norm_param();
  static const int kNormParamFieldNumber = 11;
  ::ParserModel::normParameter* mutable_norm_param(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::ParserModel::normParameter >*
      mutable_norm_param();
  const ::ParserModel::normParameter& norm_param(int index) const;
  ::ParserModel::normParameter* add_norm_param();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::ParserModel::normParameter >&
      norm_param() const;

  // string name = 1;
  void clear_name();
  static const int kNameFieldNumber = 1;
  const std::string& name() const;
  void set_name(const std::string& value);
  void set_name(std::string&& value);
  void set_name(const char* value);
  void set_name(const char* value, size_t size);
  std::string* mutable_name();
  std::string* release_name();
  void set_allocated_name(std::string* name);

  // string infer_config_type = 2;
  void clear_infer_config_type();
  static const int kInferConfigTypeFieldNumber = 2;
  const std::string& infer_config_type() const;
  void set_infer_config_type(const std::string& value);
  void set_infer_config_type(std::string&& value);
  void set_infer_config_type(const char* value);
  void set_infer_config_type(const char* value, size_t size);
  std::string* mutable_infer_config_type();
  std::string* release_infer_config_type();
  void set_allocated_infer_config_type(std::string* infer_config_type);

  // string infer_type = 3;
  void clear_infer_type();
  static const int kInferTypeFieldNumber = 3;
  const std::string& infer_type() const;
  void set_infer_type(const std::string& value);
  void set_infer_type(std::string&& value);
  void set_infer_type(const char* value);
  void set_infer_type(const char* value, size_t size);
  std::string* mutable_infer_type();
  std::string* release_infer_type();
  void set_allocated_infer_type(std::string* infer_type);

  // string model_input_data_format = 4;
  void clear_model_input_data_format();
  static const int kModelInputDataFormatFieldNumber = 4;
  const std::string& model_input_data_format() const;
  void set_model_input_data_format(const std::string& value);
  void set_model_input_data_format(std::string&& value);
  void set_model_input_data_format(const char* value);
  void set_model_input_data_format(const char* value, size_t size);
  std::string* mutable_model_input_data_format();
  std::string* release_model_input_data_format();
  void set_allocated_model_input_data_format(std::string* model_input_data_format);

  // string model_binary = 5;
  void clear_model_binary();
  static const int kModelBinaryFieldNumber = 5;
  const std::string& model_binary() const;
  void set_model_binary(const std::string& value);
  void set_model_binary(std::string&& value);
  void set_model_binary(const char* value);
  void set_model_binary(const char* value, size_t size);
  std::string* mutable_model_binary();
  std::string* release_model_binary();
  void set_allocated_model_binary(std::string* model_binary);

  // string weight_file = 6;
  void clear_weight_file();
  static const int kWeightFileFieldNumber = 6;
  const std::string& weight_file() const;
  void set_weight_file(const std::string& value);
  void set_weight_file(std::string&& value);
  void set_weight_file(const char* value);
  void set_weight_file(const char* value, size_t size);
  std::string* mutable_weight_file();
  std::string* release_weight_file();
  void set_allocated_weight_file(std::string* weight_file);

  // uint32 batch_size = 7;
  void clear_batch_size();
  static const int kBatchSizeFieldNumber = 7;
  ::PROTOBUF_NAMESPACE_ID::uint32 batch_size() const;
  void set_batch_size(::PROTOBUF_NAMESPACE_ID::uint32 value);

  // uint32 max_concurrency = 12;
  void clear_max_concurrency();
  static const int kMaxConcurrencyFieldNumber = 12;
  ::PROTOBUF_NAMESPACE_ID::uint32 max_concurrency() const;
  void set_max_concurrency(::PROTOBUF_NAMESPACE_ID::uint32 value);

  // uint32 model_position = 13;
  void clear_model_position();
  static const int kModelPositionFieldNumber = 13;
  ::PROTOBUF_NAMESPACE_ID::uint32 model_position() const;
  void set_model_position(::PROTOBUF_NAMESPACE_ID::uint32 value);

  // @@protoc_insertion_point(class_scope:ParserModel.InferConfigParameter)
 private:
  class HasBitSetters;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::ParserModel::BlobShape > input_shape_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::ParserModel::BlobShape > output_shape_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::ParserModel::meanParameter > mean_param_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::ParserModel::normParameter > norm_param_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr name_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr infer_config_type_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr infer_type_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr model_input_data_format_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr model_binary_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr weight_file_;
  ::PROTOBUF_NAMESPACE_ID::uint32 batch_size_;
  ::PROTOBUF_NAMESPACE_ID::uint32 max_concurrency_;
  ::PROTOBUF_NAMESPACE_ID::uint32 model_position_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_parser_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// BlobShape

// repeated int64 dim = 1 [packed = true];
inline int BlobShape::dim_size() const {
  return dim_.size();
}
inline void BlobShape::clear_dim() {
  dim_.Clear();
}
inline ::PROTOBUF_NAMESPACE_ID::int64 BlobShape::dim(int index) const {
  // @@protoc_insertion_point(field_get:ParserModel.BlobShape.dim)
  return dim_.Get(index);
}
inline void BlobShape::set_dim(int index, ::PROTOBUF_NAMESPACE_ID::int64 value) {
  dim_.Set(index, value);
  // @@protoc_insertion_point(field_set:ParserModel.BlobShape.dim)
}
inline void BlobShape::add_dim(::PROTOBUF_NAMESPACE_ID::int64 value) {
  dim_.Add(value);
  // @@protoc_insertion_point(field_add:ParserModel.BlobShape.dim)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int64 >&
BlobShape::dim() const {
  // @@protoc_insertion_point(field_list:ParserModel.BlobShape.dim)
  return dim_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int64 >*
BlobShape::mutable_dim() {
  // @@protoc_insertion_point(field_mutable_list:ParserModel.BlobShape.dim)
  return &dim_;
}

// -------------------------------------------------------------------

// meanParameter

// repeated float mean = 1;
inline int meanParameter::mean_size() const {
  return mean_.size();
}
inline void meanParameter::clear_mean() {
  mean_.Clear();
}
inline float meanParameter::mean(int index) const {
  // @@protoc_insertion_point(field_get:ParserModel.meanParameter.mean)
  return mean_.Get(index);
}
inline void meanParameter::set_mean(int index, float value) {
  mean_.Set(index, value);
  // @@protoc_insertion_point(field_set:ParserModel.meanParameter.mean)
}
inline void meanParameter::add_mean(float value) {
  mean_.Add(value);
  // @@protoc_insertion_point(field_add:ParserModel.meanParameter.mean)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
meanParameter::mean() const {
  // @@protoc_insertion_point(field_list:ParserModel.meanParameter.mean)
  return mean_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
meanParameter::mutable_mean() {
  // @@protoc_insertion_point(field_mutable_list:ParserModel.meanParameter.mean)
  return &mean_;
}

// -------------------------------------------------------------------

// normParameter

// repeated float norm = 1;
inline int normParameter::norm_size() const {
  return norm_.size();
}
inline void normParameter::clear_norm() {
  norm_.Clear();
}
inline float normParameter::norm(int index) const {
  // @@protoc_insertion_point(field_get:ParserModel.normParameter.norm)
  return norm_.Get(index);
}
inline void normParameter::set_norm(int index, float value) {
  norm_.Set(index, value);
  // @@protoc_insertion_point(field_set:ParserModel.normParameter.norm)
}
inline void normParameter::add_norm(float value) {
  norm_.Add(value);
  // @@protoc_insertion_point(field_add:ParserModel.normParameter.norm)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
normParameter::norm() const {
  // @@protoc_insertion_point(field_list:ParserModel.normParameter.norm)
  return norm_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
normParameter::mutable_norm() {
  // @@protoc_insertion_point(field_mutable_list:ParserModel.normParameter.norm)
  return &norm_;
}

// -------------------------------------------------------------------

// ModelParameter

// string name = 1;
inline void ModelParameter::clear_name() {
  name_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& ModelParameter::name() const {
  // @@protoc_insertion_point(field_get:ParserModel.ModelParameter.name)
  return name_.GetNoArena();
}
inline void ModelParameter::set_name(const std::string& value) {
  
  name_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:ParserModel.ModelParameter.name)
}
inline void ModelParameter::set_name(std::string&& value) {
  
  name_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:ParserModel.ModelParameter.name)
}
inline void ModelParameter::set_name(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  name_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:ParserModel.ModelParameter.name)
}
inline void ModelParameter::set_name(const char* value, size_t size) {
  
  name_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:ParserModel.ModelParameter.name)
}
inline std::string* ModelParameter::mutable_name() {
  
  // @@protoc_insertion_point(field_mutable:ParserModel.ModelParameter.name)
  return name_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* ModelParameter::release_name() {
  // @@protoc_insertion_point(field_release:ParserModel.ModelParameter.name)
  
  return name_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void ModelParameter::set_allocated_name(std::string* name) {
  if (name != nullptr) {
    
  } else {
    
  }
  name_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:ParserModel.ModelParameter.name)
}

// repeated .ParserModel.InferConfigParameter infer_config = 10;
inline int ModelParameter::infer_config_size() const {
  return infer_config_.size();
}
inline void ModelParameter::clear_infer_config() {
  infer_config_.Clear();
}
inline ::ParserModel::InferConfigParameter* ModelParameter::mutable_infer_config(int index) {
  // @@protoc_insertion_point(field_mutable:ParserModel.ModelParameter.infer_config)
  return infer_config_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::ParserModel::InferConfigParameter >*
ModelParameter::mutable_infer_config() {
  // @@protoc_insertion_point(field_mutable_list:ParserModel.ModelParameter.infer_config)
  return &infer_config_;
}
inline const ::ParserModel::InferConfigParameter& ModelParameter::infer_config(int index) const {
  // @@protoc_insertion_point(field_get:ParserModel.ModelParameter.infer_config)
  return infer_config_.Get(index);
}
inline ::ParserModel::InferConfigParameter* ModelParameter::add_infer_config() {
  // @@protoc_insertion_point(field_add:ParserModel.ModelParameter.infer_config)
  return infer_config_.Add();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::ParserModel::InferConfigParameter >&
ModelParameter::infer_config() const {
  // @@protoc_insertion_point(field_list:ParserModel.ModelParameter.infer_config)
  return infer_config_;
}

// -------------------------------------------------------------------

// InferConfigParameter

// string name = 1;
inline void InferConfigParameter::clear_name() {
  name_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& InferConfigParameter::name() const {
  // @@protoc_insertion_point(field_get:ParserModel.InferConfigParameter.name)
  return name_.GetNoArena();
}
inline void InferConfigParameter::set_name(const std::string& value) {
  
  name_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:ParserModel.InferConfigParameter.name)
}
inline void InferConfigParameter::set_name(std::string&& value) {
  
  name_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:ParserModel.InferConfigParameter.name)
}
inline void InferConfigParameter::set_name(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  name_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:ParserModel.InferConfigParameter.name)
}
inline void InferConfigParameter::set_name(const char* value, size_t size) {
  
  name_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:ParserModel.InferConfigParameter.name)
}
inline std::string* InferConfigParameter::mutable_name() {
  
  // @@protoc_insertion_point(field_mutable:ParserModel.InferConfigParameter.name)
  return name_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* InferConfigParameter::release_name() {
  // @@protoc_insertion_point(field_release:ParserModel.InferConfigParameter.name)
  
  return name_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void InferConfigParameter::set_allocated_name(std::string* name) {
  if (name != nullptr) {
    
  } else {
    
  }
  name_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:ParserModel.InferConfigParameter.name)
}

// string infer_config_type = 2;
inline void InferConfigParameter::clear_infer_config_type() {
  infer_config_type_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& InferConfigParameter::infer_config_type() const {
  // @@protoc_insertion_point(field_get:ParserModel.InferConfigParameter.infer_config_type)
  return infer_config_type_.GetNoArena();
}
inline void InferConfigParameter::set_infer_config_type(const std::string& value) {
  
  infer_config_type_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:ParserModel.InferConfigParameter.infer_config_type)
}
inline void InferConfigParameter::set_infer_config_type(std::string&& value) {
  
  infer_config_type_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:ParserModel.InferConfigParameter.infer_config_type)
}
inline void InferConfigParameter::set_infer_config_type(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  infer_config_type_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:ParserModel.InferConfigParameter.infer_config_type)
}
inline void InferConfigParameter::set_infer_config_type(const char* value, size_t size) {
  
  infer_config_type_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:ParserModel.InferConfigParameter.infer_config_type)
}
inline std::string* InferConfigParameter::mutable_infer_config_type() {
  
  // @@protoc_insertion_point(field_mutable:ParserModel.InferConfigParameter.infer_config_type)
  return infer_config_type_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* InferConfigParameter::release_infer_config_type() {
  // @@protoc_insertion_point(field_release:ParserModel.InferConfigParameter.infer_config_type)
  
  return infer_config_type_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void InferConfigParameter::set_allocated_infer_config_type(std::string* infer_config_type) {
  if (infer_config_type != nullptr) {
    
  } else {
    
  }
  infer_config_type_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), infer_config_type);
  // @@protoc_insertion_point(field_set_allocated:ParserModel.InferConfigParameter.infer_config_type)
}

// string infer_type = 3;
inline void InferConfigParameter::clear_infer_type() {
  infer_type_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& InferConfigParameter::infer_type() const {
  // @@protoc_insertion_point(field_get:ParserModel.InferConfigParameter.infer_type)
  return infer_type_.GetNoArena();
}
inline void InferConfigParameter::set_infer_type(const std::string& value) {
  
  infer_type_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:ParserModel.InferConfigParameter.infer_type)
}
inline void InferConfigParameter::set_infer_type(std::string&& value) {
  
  infer_type_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:ParserModel.InferConfigParameter.infer_type)
}
inline void InferConfigParameter::set_infer_type(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  infer_type_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:ParserModel.InferConfigParameter.infer_type)
}
inline void InferConfigParameter::set_infer_type(const char* value, size_t size) {
  
  infer_type_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:ParserModel.InferConfigParameter.infer_type)
}
inline std::string* InferConfigParameter::mutable_infer_type() {
  
  // @@protoc_insertion_point(field_mutable:ParserModel.InferConfigParameter.infer_type)
  return infer_type_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* InferConfigParameter::release_infer_type() {
  // @@protoc_insertion_point(field_release:ParserModel.InferConfigParameter.infer_type)
  
  return infer_type_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void InferConfigParameter::set_allocated_infer_type(std::string* infer_type) {
  if (infer_type != nullptr) {
    
  } else {
    
  }
  infer_type_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), infer_type);
  // @@protoc_insertion_point(field_set_allocated:ParserModel.InferConfigParameter.infer_type)
}

// string model_input_data_format = 4;
inline void InferConfigParameter::clear_model_input_data_format() {
  model_input_data_format_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& InferConfigParameter::model_input_data_format() const {
  // @@protoc_insertion_point(field_get:ParserModel.InferConfigParameter.model_input_data_format)
  return model_input_data_format_.GetNoArena();
}
inline void InferConfigParameter::set_model_input_data_format(const std::string& value) {
  
  model_input_data_format_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:ParserModel.InferConfigParameter.model_input_data_format)
}
inline void InferConfigParameter::set_model_input_data_format(std::string&& value) {
  
  model_input_data_format_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:ParserModel.InferConfigParameter.model_input_data_format)
}
inline void InferConfigParameter::set_model_input_data_format(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  model_input_data_format_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:ParserModel.InferConfigParameter.model_input_data_format)
}
inline void InferConfigParameter::set_model_input_data_format(const char* value, size_t size) {
  
  model_input_data_format_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:ParserModel.InferConfigParameter.model_input_data_format)
}
inline std::string* InferConfigParameter::mutable_model_input_data_format() {
  
  // @@protoc_insertion_point(field_mutable:ParserModel.InferConfigParameter.model_input_data_format)
  return model_input_data_format_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* InferConfigParameter::release_model_input_data_format() {
  // @@protoc_insertion_point(field_release:ParserModel.InferConfigParameter.model_input_data_format)
  
  return model_input_data_format_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void InferConfigParameter::set_allocated_model_input_data_format(std::string* model_input_data_format) {
  if (model_input_data_format != nullptr) {
    
  } else {
    
  }
  model_input_data_format_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), model_input_data_format);
  // @@protoc_insertion_point(field_set_allocated:ParserModel.InferConfigParameter.model_input_data_format)
}

// string model_binary = 5;
inline void InferConfigParameter::clear_model_binary() {
  model_binary_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& InferConfigParameter::model_binary() const {
  // @@protoc_insertion_point(field_get:ParserModel.InferConfigParameter.model_binary)
  return model_binary_.GetNoArena();
}
inline void InferConfigParameter::set_model_binary(const std::string& value) {
  
  model_binary_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:ParserModel.InferConfigParameter.model_binary)
}
inline void InferConfigParameter::set_model_binary(std::string&& value) {
  
  model_binary_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:ParserModel.InferConfigParameter.model_binary)
}
inline void InferConfigParameter::set_model_binary(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  model_binary_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:ParserModel.InferConfigParameter.model_binary)
}
inline void InferConfigParameter::set_model_binary(const char* value, size_t size) {
  
  model_binary_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:ParserModel.InferConfigParameter.model_binary)
}
inline std::string* InferConfigParameter::mutable_model_binary() {
  
  // @@protoc_insertion_point(field_mutable:ParserModel.InferConfigParameter.model_binary)
  return model_binary_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* InferConfigParameter::release_model_binary() {
  // @@protoc_insertion_point(field_release:ParserModel.InferConfigParameter.model_binary)
  
  return model_binary_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void InferConfigParameter::set_allocated_model_binary(std::string* model_binary) {
  if (model_binary != nullptr) {
    
  } else {
    
  }
  model_binary_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), model_binary);
  // @@protoc_insertion_point(field_set_allocated:ParserModel.InferConfigParameter.model_binary)
}

// string weight_file = 6;
inline void InferConfigParameter::clear_weight_file() {
  weight_file_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& InferConfigParameter::weight_file() const {
  // @@protoc_insertion_point(field_get:ParserModel.InferConfigParameter.weight_file)
  return weight_file_.GetNoArena();
}
inline void InferConfigParameter::set_weight_file(const std::string& value) {
  
  weight_file_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:ParserModel.InferConfigParameter.weight_file)
}
inline void InferConfigParameter::set_weight_file(std::string&& value) {
  
  weight_file_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:ParserModel.InferConfigParameter.weight_file)
}
inline void InferConfigParameter::set_weight_file(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  weight_file_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:ParserModel.InferConfigParameter.weight_file)
}
inline void InferConfigParameter::set_weight_file(const char* value, size_t size) {
  
  weight_file_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:ParserModel.InferConfigParameter.weight_file)
}
inline std::string* InferConfigParameter::mutable_weight_file() {
  
  // @@protoc_insertion_point(field_mutable:ParserModel.InferConfigParameter.weight_file)
  return weight_file_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* InferConfigParameter::release_weight_file() {
  // @@protoc_insertion_point(field_release:ParserModel.InferConfigParameter.weight_file)
  
  return weight_file_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void InferConfigParameter::set_allocated_weight_file(std::string* weight_file) {
  if (weight_file != nullptr) {
    
  } else {
    
  }
  weight_file_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), weight_file);
  // @@protoc_insertion_point(field_set_allocated:ParserModel.InferConfigParameter.weight_file)
}

// uint32 batch_size = 7;
inline void InferConfigParameter::clear_batch_size() {
  batch_size_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 InferConfigParameter::batch_size() const {
  // @@protoc_insertion_point(field_get:ParserModel.InferConfigParameter.batch_size)
  return batch_size_;
}
inline void InferConfigParameter::set_batch_size(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  batch_size_ = value;
  // @@protoc_insertion_point(field_set:ParserModel.InferConfigParameter.batch_size)
}

// repeated .ParserModel.BlobShape input_shape = 8;
inline int InferConfigParameter::input_shape_size() const {
  return input_shape_.size();
}
inline void InferConfigParameter::clear_input_shape() {
  input_shape_.Clear();
}
inline ::ParserModel::BlobShape* InferConfigParameter::mutable_input_shape(int index) {
  // @@protoc_insertion_point(field_mutable:ParserModel.InferConfigParameter.input_shape)
  return input_shape_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::ParserModel::BlobShape >*
InferConfigParameter::mutable_input_shape() {
  // @@protoc_insertion_point(field_mutable_list:ParserModel.InferConfigParameter.input_shape)
  return &input_shape_;
}
inline const ::ParserModel::BlobShape& InferConfigParameter::input_shape(int index) const {
  // @@protoc_insertion_point(field_get:ParserModel.InferConfigParameter.input_shape)
  return input_shape_.Get(index);
}
inline ::ParserModel::BlobShape* InferConfigParameter::add_input_shape() {
  // @@protoc_insertion_point(field_add:ParserModel.InferConfigParameter.input_shape)
  return input_shape_.Add();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::ParserModel::BlobShape >&
InferConfigParameter::input_shape() const {
  // @@protoc_insertion_point(field_list:ParserModel.InferConfigParameter.input_shape)
  return input_shape_;
}

// repeated .ParserModel.BlobShape output_shape = 9;
inline int InferConfigParameter::output_shape_size() const {
  return output_shape_.size();
}
inline void InferConfigParameter::clear_output_shape() {
  output_shape_.Clear();
}
inline ::ParserModel::BlobShape* InferConfigParameter::mutable_output_shape(int index) {
  // @@protoc_insertion_point(field_mutable:ParserModel.InferConfigParameter.output_shape)
  return output_shape_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::ParserModel::BlobShape >*
InferConfigParameter::mutable_output_shape() {
  // @@protoc_insertion_point(field_mutable_list:ParserModel.InferConfigParameter.output_shape)
  return &output_shape_;
}
inline const ::ParserModel::BlobShape& InferConfigParameter::output_shape(int index) const {
  // @@protoc_insertion_point(field_get:ParserModel.InferConfigParameter.output_shape)
  return output_shape_.Get(index);
}
inline ::ParserModel::BlobShape* InferConfigParameter::add_output_shape() {
  // @@protoc_insertion_point(field_add:ParserModel.InferConfigParameter.output_shape)
  return output_shape_.Add();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::ParserModel::BlobShape >&
InferConfigParameter::output_shape() const {
  // @@protoc_insertion_point(field_list:ParserModel.InferConfigParameter.output_shape)
  return output_shape_;
}

// repeated .ParserModel.meanParameter mean_param = 10;
inline int InferConfigParameter::mean_param_size() const {
  return mean_param_.size();
}
inline void InferConfigParameter::clear_mean_param() {
  mean_param_.Clear();
}
inline ::ParserModel::meanParameter* InferConfigParameter::mutable_mean_param(int index) {
  // @@protoc_insertion_point(field_mutable:ParserModel.InferConfigParameter.mean_param)
  return mean_param_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::ParserModel::meanParameter >*
InferConfigParameter::mutable_mean_param() {
  // @@protoc_insertion_point(field_mutable_list:ParserModel.InferConfigParameter.mean_param)
  return &mean_param_;
}
inline const ::ParserModel::meanParameter& InferConfigParameter::mean_param(int index) const {
  // @@protoc_insertion_point(field_get:ParserModel.InferConfigParameter.mean_param)
  return mean_param_.Get(index);
}
inline ::ParserModel::meanParameter* InferConfigParameter::add_mean_param() {
  // @@protoc_insertion_point(field_add:ParserModel.InferConfigParameter.mean_param)
  return mean_param_.Add();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::ParserModel::meanParameter >&
InferConfigParameter::mean_param() const {
  // @@protoc_insertion_point(field_list:ParserModel.InferConfigParameter.mean_param)
  return mean_param_;
}

// repeated .ParserModel.normParameter norm_param = 11;
inline int InferConfigParameter::norm_param_size() const {
  return norm_param_.size();
}
inline void InferConfigParameter::clear_norm_param() {
  norm_param_.Clear();
}
inline ::ParserModel::normParameter* InferConfigParameter::mutable_norm_param(int index) {
  // @@protoc_insertion_point(field_mutable:ParserModel.InferConfigParameter.norm_param)
  return norm_param_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::ParserModel::normParameter >*
InferConfigParameter::mutable_norm_param() {
  // @@protoc_insertion_point(field_mutable_list:ParserModel.InferConfigParameter.norm_param)
  return &norm_param_;
}
inline const ::ParserModel::normParameter& InferConfigParameter::norm_param(int index) const {
  // @@protoc_insertion_point(field_get:ParserModel.InferConfigParameter.norm_param)
  return norm_param_.Get(index);
}
inline ::ParserModel::normParameter* InferConfigParameter::add_norm_param() {
  // @@protoc_insertion_point(field_add:ParserModel.InferConfigParameter.norm_param)
  return norm_param_.Add();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::ParserModel::normParameter >&
InferConfigParameter::norm_param() const {
  // @@protoc_insertion_point(field_list:ParserModel.InferConfigParameter.norm_param)
  return norm_param_;
}

// uint32 max_concurrency = 12;
inline void InferConfigParameter::clear_max_concurrency() {
  max_concurrency_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 InferConfigParameter::max_concurrency() const {
  // @@protoc_insertion_point(field_get:ParserModel.InferConfigParameter.max_concurrency)
  return max_concurrency_;
}
inline void InferConfigParameter::set_max_concurrency(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  max_concurrency_ = value;
  // @@protoc_insertion_point(field_set:ParserModel.InferConfigParameter.max_concurrency)
}

// uint32 model_position = 13;
inline void InferConfigParameter::clear_model_position() {
  model_position_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 InferConfigParameter::model_position() const {
  // @@protoc_insertion_point(field_get:ParserModel.InferConfigParameter.model_position)
  return model_position_;
}
inline void InferConfigParameter::set_model_position(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  model_position_ = value;
  // @@protoc_insertion_point(field_set:ParserModel.InferConfigParameter.model_position)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace ParserModel

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_parser_2eproto
