// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: parser.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_parser_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_parser_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3015000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3015000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_parser_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_parser_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[5]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_parser_2eproto;
::PROTOBUF_NAMESPACE_ID::Metadata descriptor_table_parser_2eproto_metadata_getter(int index);
namespace ParserModel {
class BlobShape;
struct BlobShapeDefaultTypeInternal;
extern BlobShapeDefaultTypeInternal _BlobShape_default_instance_;
class InferConfigParameter;
struct InferConfigParameterDefaultTypeInternal;
extern InferConfigParameterDefaultTypeInternal _InferConfigParameter_default_instance_;
class ModelParameter;
struct ModelParameterDefaultTypeInternal;
extern ModelParameterDefaultTypeInternal _ModelParameter_default_instance_;
class meanParameter;
struct meanParameterDefaultTypeInternal;
extern meanParameterDefaultTypeInternal _meanParameter_default_instance_;
class normParameter;
struct normParameterDefaultTypeInternal;
extern normParameterDefaultTypeInternal _normParameter_default_instance_;
}  // namespace ParserModel
PROTOBUF_NAMESPACE_OPEN
template<> ::ParserModel::BlobShape* Arena::CreateMaybeMessage<::ParserModel::BlobShape>(Arena*);
template<> ::ParserModel::InferConfigParameter* Arena::CreateMaybeMessage<::ParserModel::InferConfigParameter>(Arena*);
template<> ::ParserModel::ModelParameter* Arena::CreateMaybeMessage<::ParserModel::ModelParameter>(Arena*);
template<> ::ParserModel::meanParameter* Arena::CreateMaybeMessage<::ParserModel::meanParameter>(Arena*);
template<> ::ParserModel::normParameter* Arena::CreateMaybeMessage<::ParserModel::normParameter>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace ParserModel {

// ===================================================================

class BlobShape PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:ParserModel.BlobShape) */ {
 public:
  inline BlobShape() : BlobShape(nullptr) {}
  virtual ~BlobShape();
  explicit constexpr BlobShape(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  BlobShape(const BlobShape& from);
  BlobShape(BlobShape&& from) noexcept
    : BlobShape() {
    *this = ::std::move(from);
  }

  inline BlobShape& operator=(const BlobShape& from) {
    CopyFrom(from);
    return *this;
  }
  inline BlobShape& operator=(BlobShape&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const BlobShape& default_instance() {
    return *internal_default_instance();
  }
  static inline const BlobShape* internal_default_instance() {
    return reinterpret_cast<const BlobShape*>(
               &_BlobShape_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(BlobShape& a, BlobShape& b) {
    a.Swap(&b);
  }
  inline void Swap(BlobShape* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(BlobShape* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline BlobShape* New() const final {
    return CreateMaybeMessage<BlobShape>(nullptr);
  }

  BlobShape* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<BlobShape>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const BlobShape& from);
  void MergeFrom(const BlobShape& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(BlobShape* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "ParserModel.BlobShape";
  }
  protected:
  explicit BlobShape(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    return ::descriptor_table_parser_2eproto_metadata_getter(kIndexInFileMessages);
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kDimFieldNumber = 1,
  };
  // repeated int64 dim = 1 [packed = true];
  int dim_size() const;
  private:
  int _internal_dim_size() const;
  public:
  void clear_dim();
  private:
  ::PROTOBUF_NAMESPACE_ID::int64 _internal_dim(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int64 >&
      _internal_dim() const;
  void _internal_add_dim(::PROTOBUF_NAMESPACE_ID::int64 value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int64 >*
      _internal_mutable_dim();
  public:
  ::PROTOBUF_NAMESPACE_ID::int64 dim(int index) const;
  void set_dim(int index, ::PROTOBUF_NAMESPACE_ID::int64 value);
  void add_dim(::PROTOBUF_NAMESPACE_ID::int64 value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int64 >&
      dim() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int64 >*
      mutable_dim();

  // @@protoc_insertion_point(class_scope:ParserModel.BlobShape)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int64 > dim_;
  mutable std::atomic<int> _dim_cached_byte_size_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_parser_2eproto;
};
// -------------------------------------------------------------------

class meanParameter PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:ParserModel.meanParameter) */ {
 public:
  inline meanParameter() : meanParameter(nullptr) {}
  virtual ~meanParameter();
  explicit constexpr meanParameter(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  meanParameter(const meanParameter& from);
  meanParameter(meanParameter&& from) noexcept
    : meanParameter() {
    *this = ::std::move(from);
  }

  inline meanParameter& operator=(const meanParameter& from) {
    CopyFrom(from);
    return *this;
  }
  inline meanParameter& operator=(meanParameter&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const meanParameter& default_instance() {
    return *internal_default_instance();
  }
  static inline const meanParameter* internal_default_instance() {
    return reinterpret_cast<const meanParameter*>(
               &_meanParameter_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(meanParameter& a, meanParameter& b) {
    a.Swap(&b);
  }
  inline void Swap(meanParameter* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(meanParameter* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline meanParameter* New() const final {
    return CreateMaybeMessage<meanParameter>(nullptr);
  }

  meanParameter* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<meanParameter>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const meanParameter& from);
  void MergeFrom(const meanParameter& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(meanParameter* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "ParserModel.meanParameter";
  }
  protected:
  explicit meanParameter(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    return ::descriptor_table_parser_2eproto_metadata_getter(kIndexInFileMessages);
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kMeanFieldNumber = 1,
  };
  // repeated float mean = 1;
  int mean_size() const;
  private:
  int _internal_mean_size() const;
  public:
  void clear_mean();
  private:
  float _internal_mean(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
      _internal_mean() const;
  void _internal_add_mean(float value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
      _internal_mutable_mean();
  public:
  float mean(int index) const;
  void set_mean(int index, float value);
  void add_mean(float value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
      mean() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
      mutable_mean();

  // @@protoc_insertion_point(class_scope:ParserModel.meanParameter)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< float > mean_;
  mutable std::atomic<int> _mean_cached_byte_size_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_parser_2eproto;
};
// -------------------------------------------------------------------

class normParameter PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:ParserModel.normParameter) */ {
 public:
  inline normParameter() : normParameter(nullptr) {}
  virtual ~normParameter();
  explicit constexpr normParameter(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  normParameter(const normParameter& from);
  normParameter(normParameter&& from) noexcept
    : normParameter() {
    *this = ::std::move(from);
  }

  inline normParameter& operator=(const normParameter& from) {
    CopyFrom(from);
    return *this;
  }
  inline normParameter& operator=(normParameter&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const normParameter& default_instance() {
    return *internal_default_instance();
  }
  static inline const normParameter* internal_default_instance() {
    return reinterpret_cast<const normParameter*>(
               &_normParameter_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(normParameter& a, normParameter& b) {
    a.Swap(&b);
  }
  inline void Swap(normParameter* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(normParameter* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline normParameter* New() const final {
    return CreateMaybeMessage<normParameter>(nullptr);
  }

  normParameter* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<normParameter>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const normParameter& from);
  void MergeFrom(const normParameter& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(normParameter* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "ParserModel.normParameter";
  }
  protected:
  explicit normParameter(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    return ::descriptor_table_parser_2eproto_metadata_getter(kIndexInFileMessages);
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kNormFieldNumber = 1,
  };
  // repeated float norm = 1;
  int norm_size() const;
  private:
  int _internal_norm_size() const;
  public:
  void clear_norm();
  private:
  float _internal_norm(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
      _internal_norm() const;
  void _internal_add_norm(float value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
      _internal_mutable_norm();
  public:
  float norm(int index) const;
  void set_norm(int index, float value);
  void add_norm(float value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
      norm() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
      mutable_norm();

  // @@protoc_insertion_point(class_scope:ParserModel.normParameter)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< float > norm_;
  mutable std::atomic<int> _norm_cached_byte_size_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_parser_2eproto;
};
// -------------------------------------------------------------------

class ModelParameter PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:ParserModel.ModelParameter) */ {
 public:
  inline ModelParameter() : ModelParameter(nullptr) {}
  virtual ~ModelParameter();
  explicit constexpr ModelParameter(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ModelParameter(const ModelParameter& from);
  ModelParameter(ModelParameter&& from) noexcept
    : ModelParameter() {
    *this = ::std::move(from);
  }

  inline ModelParameter& operator=(const ModelParameter& from) {
    CopyFrom(from);
    return *this;
  }
  inline ModelParameter& operator=(ModelParameter&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const ModelParameter& default_instance() {
    return *internal_default_instance();
  }
  static inline const ModelParameter* internal_default_instance() {
    return reinterpret_cast<const ModelParameter*>(
               &_ModelParameter_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(ModelParameter& a, ModelParameter& b) {
    a.Swap(&b);
  }
  inline void Swap(ModelParameter* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ModelParameter* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline ModelParameter* New() const final {
    return CreateMaybeMessage<ModelParameter>(nullptr);
  }

  ModelParameter* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<ModelParameter>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const ModelParameter& from);
  void MergeFrom(const ModelParameter& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ModelParameter* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "ParserModel.ModelParameter";
  }
  protected:
  explicit ModelParameter(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    return ::descriptor_table_parser_2eproto_metadata_getter(kIndexInFileMessages);
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kInferConfigFieldNumber = 2,
    kNameFieldNumber = 1,
  };
  // repeated .ParserModel.InferConfigParameter infer_config = 2;
  int infer_config_size() const;
  private:
  int _internal_infer_config_size() const;
  public:
  void clear_infer_config();
  ::ParserModel::InferConfigParameter* mutable_infer_config(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::ParserModel::InferConfigParameter >*
      mutable_infer_config();
  private:
  const ::ParserModel::InferConfigParameter& _internal_infer_config(int index) const;
  ::ParserModel::InferConfigParameter* _internal_add_infer_config();
  public:
  const ::ParserModel::InferConfigParameter& infer_config(int index) const;
  ::ParserModel::InferConfigParameter* add_infer_config();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::ParserModel::InferConfigParameter >&
      infer_config() const;

  // string name = 1;
  void clear_name();
  const std::string& name() const;
  void set_name(const std::string& value);
  void set_name(std::string&& value);
  void set_name(const char* value);
  void set_name(const char* value, size_t size);
  std::string* mutable_name();
  std::string* release_name();
  void set_allocated_name(std::string* name);
  private:
  const std::string& _internal_name() const;
  void _internal_set_name(const std::string& value);
  std::string* _internal_mutable_name();
  public:

  // @@protoc_insertion_point(class_scope:ParserModel.ModelParameter)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::ParserModel::InferConfigParameter > infer_config_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr name_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_parser_2eproto;
};
// -------------------------------------------------------------------

class InferConfigParameter PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:ParserModel.InferConfigParameter) */ {
 public:
  inline InferConfigParameter() : InferConfigParameter(nullptr) {}
  virtual ~InferConfigParameter();
  explicit constexpr InferConfigParameter(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  InferConfigParameter(const InferConfigParameter& from);
  InferConfigParameter(InferConfigParameter&& from) noexcept
    : InferConfigParameter() {
    *this = ::std::move(from);
  }

  inline InferConfigParameter& operator=(const InferConfigParameter& from) {
    CopyFrom(from);
    return *this;
  }
  inline InferConfigParameter& operator=(InferConfigParameter&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const InferConfigParameter& default_instance() {
    return *internal_default_instance();
  }
  static inline const InferConfigParameter* internal_default_instance() {
    return reinterpret_cast<const InferConfigParameter*>(
               &_InferConfigParameter_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(InferConfigParameter& a, InferConfigParameter& b) {
    a.Swap(&b);
  }
  inline void Swap(InferConfigParameter* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(InferConfigParameter* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline InferConfigParameter* New() const final {
    return CreateMaybeMessage<InferConfigParameter>(nullptr);
  }

  InferConfigParameter* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<InferConfigParameter>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const InferConfigParameter& from);
  void MergeFrom(const InferConfigParameter& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(InferConfigParameter* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "ParserModel.InferConfigParameter";
  }
  protected:
  explicit InferConfigParameter(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    return ::descriptor_table_parser_2eproto_metadata_getter(kIndexInFileMessages);
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kInputShapeFieldNumber = 8,
    kOutputShapeFieldNumber = 9,
    kMeanParamFieldNumber = 10,
    kNormParamFieldNumber = 11,
    kNameFieldNumber = 1,
    kInferConfigTypeFieldNumber = 2,
    kInferTypeFieldNumber = 3,
    kModelInputDataFormatFieldNumber = 4,
    kModelBinaryFieldNumber = 5,
    kWeightFileFieldNumber = 6,
    kBatchSizeFieldNumber = 7,
    kMaxConcurrencyFieldNumber = 12,
    kModelPositionFieldNumber = 13,
  };
  // repeated .ParserModel.BlobShape input_shape = 8;
  int input_shape_size() const;
  private:
  int _internal_input_shape_size() const;
  public:
  void clear_input_shape();
  ::ParserModel::BlobShape* mutable_input_shape(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::ParserModel::BlobShape >*
      mutable_input_shape();
  private:
  const ::ParserModel::BlobShape& _internal_input_shape(int index) const;
  ::ParserModel::BlobShape* _internal_add_input_shape();
  public:
  const ::ParserModel::BlobShape& input_shape(int index) const;
  ::ParserModel::BlobShape* add_input_shape();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::ParserModel::BlobShape >&
      input_shape() const;

  // repeated .ParserModel.BlobShape output_shape = 9;
  int output_shape_size() const;
  private:
  int _internal_output_shape_size() const;
  public:
  void clear_output_shape();
  ::ParserModel::BlobShape* mutable_output_shape(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::ParserModel::BlobShape >*
      mutable_output_shape();
  private:
  const ::ParserModel::BlobShape& _internal_output_shape(int index) const;
  ::ParserModel::BlobShape* _internal_add_output_shape();
  public:
  const ::ParserModel::BlobShape& output_shape(int index) const;
  ::ParserModel::BlobShape* add_output_shape();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::ParserModel::BlobShape >&
      output_shape() const;

  // repeated .ParserModel.meanParameter mean_param = 10;
  int mean_param_size() const;
  private:
  int _internal_mean_param_size() const;
  public:
  void clear_mean_param();
  ::ParserModel::meanParameter* mutable_mean_param(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::ParserModel::meanParameter >*
      mutable_mean_param();
  private:
  const ::ParserModel::meanParameter& _internal_mean_param(int index) const;
  ::ParserModel::meanParameter* _internal_add_mean_param();
  public:
  const ::ParserModel::meanParameter& mean_param(int index) const;
  ::ParserModel::meanParameter* add_mean_param();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::ParserModel::meanParameter >&
      mean_param() const;

  // repeated .ParserModel.normParameter norm_param = 11;
  int norm_param_size() const;
  private:
  int _internal_norm_param_size() const;
  public:
  void clear_norm_param();
  ::ParserModel::normParameter* mutable_norm_param(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::ParserModel::normParameter >*
      mutable_norm_param();
  private:
  const ::ParserModel::normParameter& _internal_norm_param(int index) const;
  ::ParserModel::normParameter* _internal_add_norm_param();
  public:
  const ::ParserModel::normParameter& norm_param(int index) const;
  ::ParserModel::normParameter* add_norm_param();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::ParserModel::normParameter >&
      norm_param() const;

  // string name = 1;
  void clear_name();
  const std::string& name() const;
  void set_name(const std::string& value);
  void set_name(std::string&& value);
  void set_name(const char* value);
  void set_name(const char* value, size_t size);
  std::string* mutable_name();
  std::string* release_name();
  void set_allocated_name(std::string* name);
  private:
  const std::string& _internal_name() const;
  void _internal_set_name(const std::string& value);
  std::string* _internal_mutable_name();
  public:

  // string infer_config_type = 2;
  void clear_infer_config_type();
  const std::string& infer_config_type() const;
  void set_infer_config_type(const std::string& value);
  void set_infer_config_type(std::string&& value);
  void set_infer_config_type(const char* value);
  void set_infer_config_type(const char* value, size_t size);
  std::string* mutable_infer_config_type();
  std::string* release_infer_config_type();
  void set_allocated_infer_config_type(std::string* infer_config_type);
  private:
  const std::string& _internal_infer_config_type() const;
  void _internal_set_infer_config_type(const std::string& value);
  std::string* _internal_mutable_infer_config_type();
  public:

  // string infer_type = 3;
  void clear_infer_type();
  const std::string& infer_type() const;
  void set_infer_type(const std::string& value);
  void set_infer_type(std::string&& value);
  void set_infer_type(const char* value);
  void set_infer_type(const char* value, size_t size);
  std::string* mutable_infer_type();
  std::string* release_infer_type();
  void set_allocated_infer_type(std::string* infer_type);
  private:
  const std::string& _internal_infer_type() const;
  void _internal_set_infer_type(const std::string& value);
  std::string* _internal_mutable_infer_type();
  public:

  // string model_input_data_format = 4;
  void clear_model_input_data_format();
  const std::string& model_input_data_format() const;
  void set_model_input_data_format(const std::string& value);
  void set_model_input_data_format(std::string&& value);
  void set_model_input_data_format(const char* value);
  void set_model_input_data_format(const char* value, size_t size);
  std::string* mutable_model_input_data_format();
  std::string* release_model_input_data_format();
  void set_allocated_model_input_data_format(std::string* model_input_data_format);
  private:
  const std::string& _internal_model_input_data_format() const;
  void _internal_set_model_input_data_format(const std::string& value);
  std::string* _internal_mutable_model_input_data_format();
  public:

  // string model_binary = 5;
  void clear_model_binary();
  const std::string& model_binary() const;
  void set_model_binary(const std::string& value);
  void set_model_binary(std::string&& value);
  void set_model_binary(const char* value);
  void set_model_binary(const char* value, size_t size);
  std::string* mutable_model_binary();
  std::string* release_model_binary();
  void set_allocated_model_binary(std::string* model_binary);
  private:
  const std::string& _internal_model_binary() const;
  void _internal_set_model_binary(const std::string& value);
  std::string* _internal_mutable_model_binary();
  public:

  // string weight_file = 6;
  void clear_weight_file();
  const std::string& weight_file() const;
  void set_weight_file(const std::string& value);
  void set_weight_file(std::string&& value);
  void set_weight_file(const char* value);
  void set_weight_file(const char* value, size_t size);
  std::string* mutable_weight_file();
  std::string* release_weight_file();
  void set_allocated_weight_file(std::string* weight_file);
  private:
  const std::string& _internal_weight_file() const;
  void _internal_set_weight_file(const std::string& value);
  std::string* _internal_mutable_weight_file();
  public:

  // uint32 batch_size = 7;
  void clear_batch_size();
  ::PROTOBUF_NAMESPACE_ID::uint32 batch_size() const;
  void set_batch_size(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_batch_size() const;
  void _internal_set_batch_size(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // uint32 max_concurrency = 12;
  void clear_max_concurrency();
  ::PROTOBUF_NAMESPACE_ID::uint32 max_concurrency() const;
  void set_max_concurrency(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_max_concurrency() const;
  void _internal_set_max_concurrency(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // uint32 model_position = 13;
  void clear_model_position();
  ::PROTOBUF_NAMESPACE_ID::uint32 model_position() const;
  void set_model_position(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_model_position() const;
  void _internal_set_model_position(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // @@protoc_insertion_point(class_scope:ParserModel.InferConfigParameter)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::ParserModel::BlobShape > input_shape_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::ParserModel::BlobShape > output_shape_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::ParserModel::meanParameter > mean_param_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::ParserModel::normParameter > norm_param_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr name_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr infer_config_type_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr infer_type_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr model_input_data_format_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr model_binary_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr weight_file_;
  ::PROTOBUF_NAMESPACE_ID::uint32 batch_size_;
  ::PROTOBUF_NAMESPACE_ID::uint32 max_concurrency_;
  ::PROTOBUF_NAMESPACE_ID::uint32 model_position_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_parser_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// BlobShape

// repeated int64 dim = 1 [packed = true];
inline int BlobShape::_internal_dim_size() const {
  return dim_.size();
}
inline int BlobShape::dim_size() const {
  return _internal_dim_size();
}
inline void BlobShape::clear_dim() {
  dim_.Clear();
}
inline ::PROTOBUF_NAMESPACE_ID::int64 BlobShape::_internal_dim(int index) const {
  return dim_.Get(index);
}
inline ::PROTOBUF_NAMESPACE_ID::int64 BlobShape::dim(int index) const {
  // @@protoc_insertion_point(field_get:ParserModel.BlobShape.dim)
  return _internal_dim(index);
}
inline void BlobShape::set_dim(int index, ::PROTOBUF_NAMESPACE_ID::int64 value) {
  dim_.Set(index, value);
  // @@protoc_insertion_point(field_set:ParserModel.BlobShape.dim)
}
inline void BlobShape::_internal_add_dim(::PROTOBUF_NAMESPACE_ID::int64 value) {
  dim_.Add(value);
}
inline void BlobShape::add_dim(::PROTOBUF_NAMESPACE_ID::int64 value) {
  _internal_add_dim(value);
  // @@protoc_insertion_point(field_add:ParserModel.BlobShape.dim)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int64 >&
BlobShape::_internal_dim() const {
  return dim_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int64 >&
BlobShape::dim() const {
  // @@protoc_insertion_point(field_list:ParserModel.BlobShape.dim)
  return _internal_dim();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int64 >*
BlobShape::_internal_mutable_dim() {
  return &dim_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int64 >*
BlobShape::mutable_dim() {
  // @@protoc_insertion_point(field_mutable_list:ParserModel.BlobShape.dim)
  return _internal_mutable_dim();
}

// -------------------------------------------------------------------

// meanParameter

// repeated float mean = 1;
inline int meanParameter::_internal_mean_size() const {
  return mean_.size();
}
inline int meanParameter::mean_size() const {
  return _internal_mean_size();
}
inline void meanParameter::clear_mean() {
  mean_.Clear();
}
inline float meanParameter::_internal_mean(int index) const {
  return mean_.Get(index);
}
inline float meanParameter::mean(int index) const {
  // @@protoc_insertion_point(field_get:ParserModel.meanParameter.mean)
  return _internal_mean(index);
}
inline void meanParameter::set_mean(int index, float value) {
  mean_.Set(index, value);
  // @@protoc_insertion_point(field_set:ParserModel.meanParameter.mean)
}
inline void meanParameter::_internal_add_mean(float value) {
  mean_.Add(value);
}
inline void meanParameter::add_mean(float value) {
  _internal_add_mean(value);
  // @@protoc_insertion_point(field_add:ParserModel.meanParameter.mean)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
meanParameter::_internal_mean() const {
  return mean_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
meanParameter::mean() const {
  // @@protoc_insertion_point(field_list:ParserModel.meanParameter.mean)
  return _internal_mean();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
meanParameter::_internal_mutable_mean() {
  return &mean_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
meanParameter::mutable_mean() {
  // @@protoc_insertion_point(field_mutable_list:ParserModel.meanParameter.mean)
  return _internal_mutable_mean();
}

// -------------------------------------------------------------------

// normParameter

// repeated float norm = 1;
inline int normParameter::_internal_norm_size() const {
  return norm_.size();
}
inline int normParameter::norm_size() const {
  return _internal_norm_size();
}
inline void normParameter::clear_norm() {
  norm_.Clear();
}
inline float normParameter::_internal_norm(int index) const {
  return norm_.Get(index);
}
inline float normParameter::norm(int index) const {
  // @@protoc_insertion_point(field_get:ParserModel.normParameter.norm)
  return _internal_norm(index);
}
inline void normParameter::set_norm(int index, float value) {
  norm_.Set(index, value);
  // @@protoc_insertion_point(field_set:ParserModel.normParameter.norm)
}
inline void normParameter::_internal_add_norm(float value) {
  norm_.Add(value);
}
inline void normParameter::add_norm(float value) {
  _internal_add_norm(value);
  // @@protoc_insertion_point(field_add:ParserModel.normParameter.norm)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
normParameter::_internal_norm() const {
  return norm_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
normParameter::norm() const {
  // @@protoc_insertion_point(field_list:ParserModel.normParameter.norm)
  return _internal_norm();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
normParameter::_internal_mutable_norm() {
  return &norm_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
normParameter::mutable_norm() {
  // @@protoc_insertion_point(field_mutable_list:ParserModel.normParameter.norm)
  return _internal_mutable_norm();
}

// -------------------------------------------------------------------

// ModelParameter

// string name = 1;
inline void ModelParameter::clear_name() {
  name_.ClearToEmpty();
}
inline const std::string& ModelParameter::name() const {
  // @@protoc_insertion_point(field_get:ParserModel.ModelParameter.name)
  return _internal_name();
}
inline void ModelParameter::set_name(const std::string& value) {
  _internal_set_name(value);
  // @@protoc_insertion_point(field_set:ParserModel.ModelParameter.name)
}
inline std::string* ModelParameter::mutable_name() {
  // @@protoc_insertion_point(field_mutable:ParserModel.ModelParameter.name)
  return _internal_mutable_name();
}
inline const std::string& ModelParameter::_internal_name() const {
  return name_.Get();
}
inline void ModelParameter::_internal_set_name(const std::string& value) {
  
  name_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void ModelParameter::set_name(std::string&& value) {
  
  name_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:ParserModel.ModelParameter.name)
}
inline void ModelParameter::set_name(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  name_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:ParserModel.ModelParameter.name)
}
inline void ModelParameter::set_name(const char* value,
    size_t size) {
  
  name_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:ParserModel.ModelParameter.name)
}
inline std::string* ModelParameter::_internal_mutable_name() {
  
  return name_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* ModelParameter::release_name() {
  // @@protoc_insertion_point(field_release:ParserModel.ModelParameter.name)
  return name_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void ModelParameter::set_allocated_name(std::string* name) {
  if (name != nullptr) {
    
  } else {
    
  }
  name_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), name,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:ParserModel.ModelParameter.name)
}

// repeated .ParserModel.InferConfigParameter infer_config = 2;
inline int ModelParameter::_internal_infer_config_size() const {
  return infer_config_.size();
}
inline int ModelParameter::infer_config_size() const {
  return _internal_infer_config_size();
}
inline void ModelParameter::clear_infer_config() {
  infer_config_.Clear();
}
inline ::ParserModel::InferConfigParameter* ModelParameter::mutable_infer_config(int index) {
  // @@protoc_insertion_point(field_mutable:ParserModel.ModelParameter.infer_config)
  return infer_config_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::ParserModel::InferConfigParameter >*
ModelParameter::mutable_infer_config() {
  // @@protoc_insertion_point(field_mutable_list:ParserModel.ModelParameter.infer_config)
  return &infer_config_;
}
inline const ::ParserModel::InferConfigParameter& ModelParameter::_internal_infer_config(int index) const {
  return infer_config_.Get(index);
}
inline const ::ParserModel::InferConfigParameter& ModelParameter::infer_config(int index) const {
  // @@protoc_insertion_point(field_get:ParserModel.ModelParameter.infer_config)
  return _internal_infer_config(index);
}
inline ::ParserModel::InferConfigParameter* ModelParameter::_internal_add_infer_config() {
  return infer_config_.Add();
}
inline ::ParserModel::InferConfigParameter* ModelParameter::add_infer_config() {
  // @@protoc_insertion_point(field_add:ParserModel.ModelParameter.infer_config)
  return _internal_add_infer_config();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::ParserModel::InferConfigParameter >&
ModelParameter::infer_config() const {
  // @@protoc_insertion_point(field_list:ParserModel.ModelParameter.infer_config)
  return infer_config_;
}

// -------------------------------------------------------------------

// InferConfigParameter

// string name = 1;
inline void InferConfigParameter::clear_name() {
  name_.ClearToEmpty();
}
inline const std::string& InferConfigParameter::name() const {
  // @@protoc_insertion_point(field_get:ParserModel.InferConfigParameter.name)
  return _internal_name();
}
inline void InferConfigParameter::set_name(const std::string& value) {
  _internal_set_name(value);
  // @@protoc_insertion_point(field_set:ParserModel.InferConfigParameter.name)
}
inline std::string* InferConfigParameter::mutable_name() {
  // @@protoc_insertion_point(field_mutable:ParserModel.InferConfigParameter.name)
  return _internal_mutable_name();
}
inline const std::string& InferConfigParameter::_internal_name() const {
  return name_.Get();
}
inline void InferConfigParameter::_internal_set_name(const std::string& value) {
  
  name_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void InferConfigParameter::set_name(std::string&& value) {
  
  name_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:ParserModel.InferConfigParameter.name)
}
inline void InferConfigParameter::set_name(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  name_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:ParserModel.InferConfigParameter.name)
}
inline void InferConfigParameter::set_name(const char* value,
    size_t size) {
  
  name_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:ParserModel.InferConfigParameter.name)
}
inline std::string* InferConfigParameter::_internal_mutable_name() {
  
  return name_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* InferConfigParameter::release_name() {
  // @@protoc_insertion_point(field_release:ParserModel.InferConfigParameter.name)
  return name_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void InferConfigParameter::set_allocated_name(std::string* name) {
  if (name != nullptr) {
    
  } else {
    
  }
  name_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), name,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:ParserModel.InferConfigParameter.name)
}

// string infer_config_type = 2;
inline void InferConfigParameter::clear_infer_config_type() {
  infer_config_type_.ClearToEmpty();
}
inline const std::string& InferConfigParameter::infer_config_type() const {
  // @@protoc_insertion_point(field_get:ParserModel.InferConfigParameter.infer_config_type)
  return _internal_infer_config_type();
}
inline void InferConfigParameter::set_infer_config_type(const std::string& value) {
  _internal_set_infer_config_type(value);
  // @@protoc_insertion_point(field_set:ParserModel.InferConfigParameter.infer_config_type)
}
inline std::string* InferConfigParameter::mutable_infer_config_type() {
  // @@protoc_insertion_point(field_mutable:ParserModel.InferConfigParameter.infer_config_type)
  return _internal_mutable_infer_config_type();
}
inline const std::string& InferConfigParameter::_internal_infer_config_type() const {
  return infer_config_type_.Get();
}
inline void InferConfigParameter::_internal_set_infer_config_type(const std::string& value) {
  
  infer_config_type_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void InferConfigParameter::set_infer_config_type(std::string&& value) {
  
  infer_config_type_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:ParserModel.InferConfigParameter.infer_config_type)
}
inline void InferConfigParameter::set_infer_config_type(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  infer_config_type_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:ParserModel.InferConfigParameter.infer_config_type)
}
inline void InferConfigParameter::set_infer_config_type(const char* value,
    size_t size) {
  
  infer_config_type_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:ParserModel.InferConfigParameter.infer_config_type)
}
inline std::string* InferConfigParameter::_internal_mutable_infer_config_type() {
  
  return infer_config_type_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* InferConfigParameter::release_infer_config_type() {
  // @@protoc_insertion_point(field_release:ParserModel.InferConfigParameter.infer_config_type)
  return infer_config_type_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void InferConfigParameter::set_allocated_infer_config_type(std::string* infer_config_type) {
  if (infer_config_type != nullptr) {
    
  } else {
    
  }
  infer_config_type_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), infer_config_type,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:ParserModel.InferConfigParameter.infer_config_type)
}

// string infer_type = 3;
inline void InferConfigParameter::clear_infer_type() {
  infer_type_.ClearToEmpty();
}
inline const std::string& InferConfigParameter::infer_type() const {
  // @@protoc_insertion_point(field_get:ParserModel.InferConfigParameter.infer_type)
  return _internal_infer_type();
}
inline void InferConfigParameter::set_infer_type(const std::string& value) {
  _internal_set_infer_type(value);
  // @@protoc_insertion_point(field_set:ParserModel.InferConfigParameter.infer_type)
}
inline std::string* InferConfigParameter::mutable_infer_type() {
  // @@protoc_insertion_point(field_mutable:ParserModel.InferConfigParameter.infer_type)
  return _internal_mutable_infer_type();
}
inline const std::string& InferConfigParameter::_internal_infer_type() const {
  return infer_type_.Get();
}
inline void InferConfigParameter::_internal_set_infer_type(const std::string& value) {
  
  infer_type_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void InferConfigParameter::set_infer_type(std::string&& value) {
  
  infer_type_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:ParserModel.InferConfigParameter.infer_type)
}
inline void InferConfigParameter::set_infer_type(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  infer_type_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:ParserModel.InferConfigParameter.infer_type)
}
inline void InferConfigParameter::set_infer_type(const char* value,
    size_t size) {
  
  infer_type_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:ParserModel.InferConfigParameter.infer_type)
}
inline std::string* InferConfigParameter::_internal_mutable_infer_type() {
  
  return infer_type_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* InferConfigParameter::release_infer_type() {
  // @@protoc_insertion_point(field_release:ParserModel.InferConfigParameter.infer_type)
  return infer_type_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void InferConfigParameter::set_allocated_infer_type(std::string* infer_type) {
  if (infer_type != nullptr) {
    
  } else {
    
  }
  infer_type_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), infer_type,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:ParserModel.InferConfigParameter.infer_type)
}

// string model_input_data_format = 4;
inline void InferConfigParameter::clear_model_input_data_format() {
  model_input_data_format_.ClearToEmpty();
}
inline const std::string& InferConfigParameter::model_input_data_format() const {
  // @@protoc_insertion_point(field_get:ParserModel.InferConfigParameter.model_input_data_format)
  return _internal_model_input_data_format();
}
inline void InferConfigParameter::set_model_input_data_format(const std::string& value) {
  _internal_set_model_input_data_format(value);
  // @@protoc_insertion_point(field_set:ParserModel.InferConfigParameter.model_input_data_format)
}
inline std::string* InferConfigParameter::mutable_model_input_data_format() {
  // @@protoc_insertion_point(field_mutable:ParserModel.InferConfigParameter.model_input_data_format)
  return _internal_mutable_model_input_data_format();
}
inline const std::string& InferConfigParameter::_internal_model_input_data_format() const {
  return model_input_data_format_.Get();
}
inline void InferConfigParameter::_internal_set_model_input_data_format(const std::string& value) {
  
  model_input_data_format_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void InferConfigParameter::set_model_input_data_format(std::string&& value) {
  
  model_input_data_format_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:ParserModel.InferConfigParameter.model_input_data_format)
}
inline void InferConfigParameter::set_model_input_data_format(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  model_input_data_format_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:ParserModel.InferConfigParameter.model_input_data_format)
}
inline void InferConfigParameter::set_model_input_data_format(const char* value,
    size_t size) {
  
  model_input_data_format_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:ParserModel.InferConfigParameter.model_input_data_format)
}
inline std::string* InferConfigParameter::_internal_mutable_model_input_data_format() {
  
  return model_input_data_format_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* InferConfigParameter::release_model_input_data_format() {
  // @@protoc_insertion_point(field_release:ParserModel.InferConfigParameter.model_input_data_format)
  return model_input_data_format_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void InferConfigParameter::set_allocated_model_input_data_format(std::string* model_input_data_format) {
  if (model_input_data_format != nullptr) {
    
  } else {
    
  }
  model_input_data_format_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), model_input_data_format,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:ParserModel.InferConfigParameter.model_input_data_format)
}

// string model_binary = 5;
inline void InferConfigParameter::clear_model_binary() {
  model_binary_.ClearToEmpty();
}
inline const std::string& InferConfigParameter::model_binary() const {
  // @@protoc_insertion_point(field_get:ParserModel.InferConfigParameter.model_binary)
  return _internal_model_binary();
}
inline void InferConfigParameter::set_model_binary(const std::string& value) {
  _internal_set_model_binary(value);
  // @@protoc_insertion_point(field_set:ParserModel.InferConfigParameter.model_binary)
}
inline std::string* InferConfigParameter::mutable_model_binary() {
  // @@protoc_insertion_point(field_mutable:ParserModel.InferConfigParameter.model_binary)
  return _internal_mutable_model_binary();
}
inline const std::string& InferConfigParameter::_internal_model_binary() const {
  return model_binary_.Get();
}
inline void InferConfigParameter::_internal_set_model_binary(const std::string& value) {
  
  model_binary_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void InferConfigParameter::set_model_binary(std::string&& value) {
  
  model_binary_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:ParserModel.InferConfigParameter.model_binary)
}
inline void InferConfigParameter::set_model_binary(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  model_binary_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:ParserModel.InferConfigParameter.model_binary)
}
inline void InferConfigParameter::set_model_binary(const char* value,
    size_t size) {
  
  model_binary_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:ParserModel.InferConfigParameter.model_binary)
}
inline std::string* InferConfigParameter::_internal_mutable_model_binary() {
  
  return model_binary_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* InferConfigParameter::release_model_binary() {
  // @@protoc_insertion_point(field_release:ParserModel.InferConfigParameter.model_binary)
  return model_binary_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void InferConfigParameter::set_allocated_model_binary(std::string* model_binary) {
  if (model_binary != nullptr) {
    
  } else {
    
  }
  model_binary_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), model_binary,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:ParserModel.InferConfigParameter.model_binary)
}

// string weight_file = 6;
inline void InferConfigParameter::clear_weight_file() {
  weight_file_.ClearToEmpty();
}
inline const std::string& InferConfigParameter::weight_file() const {
  // @@protoc_insertion_point(field_get:ParserModel.InferConfigParameter.weight_file)
  return _internal_weight_file();
}
inline void InferConfigParameter::set_weight_file(const std::string& value) {
  _internal_set_weight_file(value);
  // @@protoc_insertion_point(field_set:ParserModel.InferConfigParameter.weight_file)
}
inline std::string* InferConfigParameter::mutable_weight_file() {
  // @@protoc_insertion_point(field_mutable:ParserModel.InferConfigParameter.weight_file)
  return _internal_mutable_weight_file();
}
inline const std::string& InferConfigParameter::_internal_weight_file() const {
  return weight_file_.Get();
}
inline void InferConfigParameter::_internal_set_weight_file(const std::string& value) {
  
  weight_file_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void InferConfigParameter::set_weight_file(std::string&& value) {
  
  weight_file_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:ParserModel.InferConfigParameter.weight_file)
}
inline void InferConfigParameter::set_weight_file(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  weight_file_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:ParserModel.InferConfigParameter.weight_file)
}
inline void InferConfigParameter::set_weight_file(const char* value,
    size_t size) {
  
  weight_file_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:ParserModel.InferConfigParameter.weight_file)
}
inline std::string* InferConfigParameter::_internal_mutable_weight_file() {
  
  return weight_file_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* InferConfigParameter::release_weight_file() {
  // @@protoc_insertion_point(field_release:ParserModel.InferConfigParameter.weight_file)
  return weight_file_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void InferConfigParameter::set_allocated_weight_file(std::string* weight_file) {
  if (weight_file != nullptr) {
    
  } else {
    
  }
  weight_file_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), weight_file,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:ParserModel.InferConfigParameter.weight_file)
}

// uint32 batch_size = 7;
inline void InferConfigParameter::clear_batch_size() {
  batch_size_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 InferConfigParameter::_internal_batch_size() const {
  return batch_size_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 InferConfigParameter::batch_size() const {
  // @@protoc_insertion_point(field_get:ParserModel.InferConfigParameter.batch_size)
  return _internal_batch_size();
}
inline void InferConfigParameter::_internal_set_batch_size(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  batch_size_ = value;
}
inline void InferConfigParameter::set_batch_size(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_batch_size(value);
  // @@protoc_insertion_point(field_set:ParserModel.InferConfigParameter.batch_size)
}

// repeated .ParserModel.BlobShape input_shape = 8;
inline int InferConfigParameter::_internal_input_shape_size() const {
  return input_shape_.size();
}
inline int InferConfigParameter::input_shape_size() const {
  return _internal_input_shape_size();
}
inline void InferConfigParameter::clear_input_shape() {
  input_shape_.Clear();
}
inline ::ParserModel::BlobShape* InferConfigParameter::mutable_input_shape(int index) {
  // @@protoc_insertion_point(field_mutable:ParserModel.InferConfigParameter.input_shape)
  return input_shape_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::ParserModel::BlobShape >*
InferConfigParameter::mutable_input_shape() {
  // @@protoc_insertion_point(field_mutable_list:ParserModel.InferConfigParameter.input_shape)
  return &input_shape_;
}
inline const ::ParserModel::BlobShape& InferConfigParameter::_internal_input_shape(int index) const {
  return input_shape_.Get(index);
}
inline const ::ParserModel::BlobShape& InferConfigParameter::input_shape(int index) const {
  // @@protoc_insertion_point(field_get:ParserModel.InferConfigParameter.input_shape)
  return _internal_input_shape(index);
}
inline ::ParserModel::BlobShape* InferConfigParameter::_internal_add_input_shape() {
  return input_shape_.Add();
}
inline ::ParserModel::BlobShape* InferConfigParameter::add_input_shape() {
  // @@protoc_insertion_point(field_add:ParserModel.InferConfigParameter.input_shape)
  return _internal_add_input_shape();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::ParserModel::BlobShape >&
InferConfigParameter::input_shape() const {
  // @@protoc_insertion_point(field_list:ParserModel.InferConfigParameter.input_shape)
  return input_shape_;
}

// repeated .ParserModel.BlobShape output_shape = 9;
inline int InferConfigParameter::_internal_output_shape_size() const {
  return output_shape_.size();
}
inline int InferConfigParameter::output_shape_size() const {
  return _internal_output_shape_size();
}
inline void InferConfigParameter::clear_output_shape() {
  output_shape_.Clear();
}
inline ::ParserModel::BlobShape* InferConfigParameter::mutable_output_shape(int index) {
  // @@protoc_insertion_point(field_mutable:ParserModel.InferConfigParameter.output_shape)
  return output_shape_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::ParserModel::BlobShape >*
InferConfigParameter::mutable_output_shape() {
  // @@protoc_insertion_point(field_mutable_list:ParserModel.InferConfigParameter.output_shape)
  return &output_shape_;
}
inline const ::ParserModel::BlobShape& InferConfigParameter::_internal_output_shape(int index) const {
  return output_shape_.Get(index);
}
inline const ::ParserModel::BlobShape& InferConfigParameter::output_shape(int index) const {
  // @@protoc_insertion_point(field_get:ParserModel.InferConfigParameter.output_shape)
  return _internal_output_shape(index);
}
inline ::ParserModel::BlobShape* InferConfigParameter::_internal_add_output_shape() {
  return output_shape_.Add();
}
inline ::ParserModel::BlobShape* InferConfigParameter::add_output_shape() {
  // @@protoc_insertion_point(field_add:ParserModel.InferConfigParameter.output_shape)
  return _internal_add_output_shape();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::ParserModel::BlobShape >&
InferConfigParameter::output_shape() const {
  // @@protoc_insertion_point(field_list:ParserModel.InferConfigParameter.output_shape)
  return output_shape_;
}

// repeated .ParserModel.meanParameter mean_param = 10;
inline int InferConfigParameter::_internal_mean_param_size() const {
  return mean_param_.size();
}
inline int InferConfigParameter::mean_param_size() const {
  return _internal_mean_param_size();
}
inline void InferConfigParameter::clear_mean_param() {
  mean_param_.Clear();
}
inline ::ParserModel::meanParameter* InferConfigParameter::mutable_mean_param(int index) {
  // @@protoc_insertion_point(field_mutable:ParserModel.InferConfigParameter.mean_param)
  return mean_param_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::ParserModel::meanParameter >*
InferConfigParameter::mutable_mean_param() {
  // @@protoc_insertion_point(field_mutable_list:ParserModel.InferConfigParameter.mean_param)
  return &mean_param_;
}
inline const ::ParserModel::meanParameter& InferConfigParameter::_internal_mean_param(int index) const {
  return mean_param_.Get(index);
}
inline const ::ParserModel::meanParameter& InferConfigParameter::mean_param(int index) const {
  // @@protoc_insertion_point(field_get:ParserModel.InferConfigParameter.mean_param)
  return _internal_mean_param(index);
}
inline ::ParserModel::meanParameter* InferConfigParameter::_internal_add_mean_param() {
  return mean_param_.Add();
}
inline ::ParserModel::meanParameter* InferConfigParameter::add_mean_param() {
  // @@protoc_insertion_point(field_add:ParserModel.InferConfigParameter.mean_param)
  return _internal_add_mean_param();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::ParserModel::meanParameter >&
InferConfigParameter::mean_param() const {
  // @@protoc_insertion_point(field_list:ParserModel.InferConfigParameter.mean_param)
  return mean_param_;
}

// repeated .ParserModel.normParameter norm_param = 11;
inline int InferConfigParameter::_internal_norm_param_size() const {
  return norm_param_.size();
}
inline int InferConfigParameter::norm_param_size() const {
  return _internal_norm_param_size();
}
inline void InferConfigParameter::clear_norm_param() {
  norm_param_.Clear();
}
inline ::ParserModel::normParameter* InferConfigParameter::mutable_norm_param(int index) {
  // @@protoc_insertion_point(field_mutable:ParserModel.InferConfigParameter.norm_param)
  return norm_param_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::ParserModel::normParameter >*
InferConfigParameter::mutable_norm_param() {
  // @@protoc_insertion_point(field_mutable_list:ParserModel.InferConfigParameter.norm_param)
  return &norm_param_;
}
inline const ::ParserModel::normParameter& InferConfigParameter::_internal_norm_param(int index) const {
  return norm_param_.Get(index);
}
inline const ::ParserModel::normParameter& InferConfigParameter::norm_param(int index) const {
  // @@protoc_insertion_point(field_get:ParserModel.InferConfigParameter.norm_param)
  return _internal_norm_param(index);
}
inline ::ParserModel::normParameter* InferConfigParameter::_internal_add_norm_param() {
  return norm_param_.Add();
}
inline ::ParserModel::normParameter* InferConfigParameter::add_norm_param() {
  // @@protoc_insertion_point(field_add:ParserModel.InferConfigParameter.norm_param)
  return _internal_add_norm_param();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::ParserModel::normParameter >&
InferConfigParameter::norm_param() const {
  // @@protoc_insertion_point(field_list:ParserModel.InferConfigParameter.norm_param)
  return norm_param_;
}

// uint32 max_concurrency = 12;
inline void InferConfigParameter::clear_max_concurrency() {
  max_concurrency_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 InferConfigParameter::_internal_max_concurrency() const {
  return max_concurrency_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 InferConfigParameter::max_concurrency() const {
  // @@protoc_insertion_point(field_get:ParserModel.InferConfigParameter.max_concurrency)
  return _internal_max_concurrency();
}
inline void InferConfigParameter::_internal_set_max_concurrency(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  max_concurrency_ = value;
}
inline void InferConfigParameter::set_max_concurrency(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_max_concurrency(value);
  // @@protoc_insertion_point(field_set:ParserModel.InferConfigParameter.max_concurrency)
}

// uint32 model_position = 13;
inline void InferConfigParameter::clear_model_position() {
  model_position_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 InferConfigParameter::_internal_model_position() const {
  return model_position_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 InferConfigParameter::model_position() const {
  // @@protoc_insertion_point(field_get:ParserModel.InferConfigParameter.model_position)
  return _internal_model_position();
}
inline void InferConfigParameter::_internal_set_model_position(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  model_position_ = value;
}
inline void InferConfigParameter::set_model_position(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_model_position(value);
  // @@protoc_insertion_point(field_set:ParserModel.InferConfigParameter.model_position)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace ParserModel

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_parser_2eproto
